# Generated by Django 4.2.1 on 2023-05-15 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrakingInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoiceNo', models.CharField(max_length=30)),
                ('productName', models.CharField(max_length=30)),
                ('receiverName', models.CharField(max_length=50)),
                ('receiverPhone', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=50)),
                ('street', models.CharField(max_length=100)),
                ('details', models.CharField(max_length=50)),
                ('zipcode', models.CharField(max_length=50)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
