# Generated by Django 4.2.1 on 2023-05-15 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('input', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trakinginfo',
            name='company',
            field=models.CharField(default='', max_length=50),
        ),
    ]
