# Generated by Django 4.2 on 2023-05-16 06:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('input', '0002_trakinginfo_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trakinginfo',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
