# Generated by Django 4.2 on 2023-05-16 06:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('input', '0004_alter_trakinginfo_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trakinginfo',
            name='id',
        ),
        migrations.AddField(
            model_name='trakinginfo',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
